name=usertools
service=cpanel
url=/frontend/jupiter/3rdparty/usertools/usertools.live.pl
entryurl=3rdparty/usertools/usertools.live.pl
displayname=Ferramentas
icon=fas fa-tools
itemgroup=advanced
feature=usertools
user=cpanel
